@"
#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as the first argument. For example:
#       'sh /path/to/gradlew' with ksh or bash, assuming they are installed.
#       Also note that 'sh' will fallback to an incompatible shell if /bin/sh
#       is not POSIX-compliant and no other shell is available.
#
#   (2) This script attempts to detect the current Java installation and uses
#       that to run Gradle. If it cannot detect a Java installation, Gradle
#       will not run. If this occurs, please set the JAVA_HOME environment
#       variable to point to a Java installation that is at or above the
#       required version.
#
#   (3) This script uses the Gradle wrapper JAR file to run Gradle. This JAR
#       file is usually stored in the 'gradle/wrapper' directory. You can
#       specify the location of this JAR file using the GRADLE_WRAPPER_JAR
#       environment variable.
#
#   (4) This script uses the GRADLE_OPTS environment variable to pass JVM
#       arguments to Gradle. If you have set GRADLE_OPTS, the script will
#       pass them to the Gradle JVM.
#
#   (5) The script uses the GRADLE_APP_NAME variable to set the name of the
#       Gradle application. You can set this variable to change the name
#       displayed in the console output.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=\$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=\${app_path%"${app_path##*/}"} 2>/dev/null
    [ -d "\$APP_HOME" ]
do
    # ls uses the POSIXLY_CORRECT environment variable to attempt to
    # resolve links correctly, and if that fails, it uses the -h option.
    # This is necessary to support the -h option on all POSIX-compliant
    # shells. If 'ls' is run with the -h option, the link is followed.
    lsout=\`ls -ld "\$app_path"\`
    link=\`expr "\$lsout" : '.*-> \(.*\)$'\`
    if [ "\$link" ]; then
        app_path=\$link
    else
        app_path=\`dirname "\$app_path"\`
    fi
done

APP_HOME="\$(cd "\$APP_HOME" && pwd)" || exit

APP_NAME="Gradle"
APP_BASE_NAME=\${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "\$*"
} >&2

die () {
    echo
    echo "\$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "\$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=\$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "\$JAVA_HOME" ] ; then
    if [ -x "\$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="\$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="\$JAVA_HOME/bin/java"
    fi
    if [ ! -x "\$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: \$JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case \$MAX_FD in #(
      max*)
        MAX_FD=\$(ulimit -H -n) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case \$MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "\$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to \$MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * the -classpath argument
#   * the -D... app name arguments
#   * the -D... JVM arguments
#   * the -D... default JVM arguments
#   * the JAVA_OPTS environment variable
#   * the GRADLE_OPTS environment variable
#   * the GRADLE_APP_NAME environment variable

set -- \\
        "-Dorg.gradle.appname=\$APP_BASE_NAME" \\
        -classpath "\$CLASSPATH" \\
        org.gradle.wrapper.GradleWrapperMain \\
        "\$@"

# Use "xargs" to parse quoted args.

# Use -E to preserve environment variables.
exec "\$JAVACMD" "\$@"
"@ | Out-File -FilePath "C:\BAZA-main\gradlew" -Encoding utf8 -NoNewline